Argument parsing
wilmhit/elegant-graph-coloring pull request #1
Opened 2021-04-17 15:08 UTC by wilmhit

2021-04-17 15:53 UTC, songofroland requested changes

2021-04-17 15:53 UTC, songofroland commented on graph-coloring/__main__.py
> +from files import *
In general it's a bad practice. It's better to import everything explicitly

Also, the name _files_ sound for me like a 3rd party package, let's rename it.

2021-04-17 15:53 UTC, songofroland commented on graph-coloring/__main__.py
> +parser.add_argument('GRAPH', type=str, help="Text file containing graph")
so this will go like `script.py GRAPH my_file.txt` ?

2021-04-17 15:53 UTC, songofroland commented on graph-coloring/__main__.py
> +def process_graph(graph) -> None: pass
Don't take it personal but it hurts my eyes. When reading this I feel that the function is incorrect. Let's go with:
```
def process_graph(graph) -> None: 
    pass
```

2021-04-17 15:53 UTC, songofroland commented on graph-coloring/__main__.py
> +def main(args):
please add type to `args`

2021-04-17 15:53 UTC, songofroland commented on graph-coloring/files.py
> +def get_graph_file(filename: str) -> str: pass
Same here

2021-04-17 15:53 UTC, songofroland commented on reqirements.dev
> +yapf==0.31.0
Typo in filename. Also let's better use extension `.txt`.  (for IDE's it's better)

Ideally, let's use `poetry` or `pipenv` but it does not matter that much.

2021-04-17 17:54 UTC, wilmhit commented on graph-coloring/__main__.py
> +parser.add_argument('GRAPH', type=str, help="Text file containing graph")
no script.py myfile.txt

2021-04-17 17:55 UTC, wilmhit commented on reqirements.dev
> +yapf==0.31.0
its dev dependencies

2021-04-17 18:28 UTC, wilmhit commented on reqirements.dev
> +yapf==0.31.0
I dont really like poetry, but sure we can use pipenv. Maybe next merge

2021-04-18 20:07 UTC, songofroland approved these changes

2021-04-19 17:12 UTC, merged