Color graphs by utilizing CSP paradigmates
wilmhit/elegant-graph-coloring pull request #11
Opened 2021-06-20 18:44 UTC by songofroland

2021-06-21 13:53 UTC, wilmhit requested changes

2021-06-21 13:53 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    edges_colors = [el for row in edges for el in row if el != 0]
This line is unreadable

2021-06-21 13:53 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    edges_colors = [el for row in edges for el in row if el != 0]
You can checkout graph_utils.py  from fix/validation if you need to count edges

2021-06-21 13:53 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    edges_set = set(edges_colors)
I don't see a reason for using sets here. All operations below this point can be performed on lists as well.

2021-06-21 13:53 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    edges_set = set(edges_colors)
Oh i see now

2021-06-21 13:53 UTC, wilmhit commented on tests/test_graph_coloring.py
> +def assert_colored_elegantly(edges: list, vertices: list) -> None:
Use AdjMatrix type for edges

2021-06-21 13:55 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    edges_colors = [el for row in edges for el in row if el != 0]
you could use `filter` function here

2021-06-23 18:26 UTC, songofroland commented on graph_coloring/graph_utils.py
> +    return sum(sum(element > 0 for element in row) for row in graph) // 2
Your method was really interesting but a little bit overcomplicated. As a daily Python user, I'd say this one is more readable.

2021-06-23 18:33 UTC, songofroland commented on tests/test_graph_coloring.py
> +    edges_colors = [el for row in edges for el in row if el != 0]
thanks for the idea, although in my opinion list comprehension solution is more readable
when you'll get more experience with Python, you'll feel very comfortable with using them

![image](https://user-images.githubusercontent.com/46332508/123149815-f7d85c00-d461-11eb-8d5f-943a4ccea936.png)

2021-06-23 18:36 UTC, songofroland commented on tests/test_graph_coloring.py
> +    edges_colors = [el for row in edges for el in row if el != 0]
I'm not stubborn tho, if u insist to use the second one then I could adjust it

2021-06-24 11:32 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    edges_colors = [el for row in edges for el in row if el != 0]
List comprehension are fine. It's just this one is very complicated.

2021-06-24 11:36 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    edges_colors = [el for row in edges for el in row if el != 0]
How about:
```python
filter(lambda color: color !=0,  [color for color in row for row in edges])
```
but ultimately it's your choice

2021-06-24 11:37 UTC, wilmhit approved these changes

2021-06-24 15:42 UTC, merged