Fix validation and vertex labels
wilmhit/elegant-graph-coloring pull request #12
Opened 2021-06-21 16:39 UTC by wilmhit

2021-06-23 18:50 UTC, songofroland reviewed
I'd approve this, but due to MR order and function `get_edges_and_labels` I can't

2021-06-23 18:50 UTC, songofroland commented on graph_coloring/config.py
>  BASE_DIR = Path(__file__).parent.absolute()
it's redundant now

2021-06-23 18:50 UTC, songofroland commented on graph_coloring/graph_utils.py
> +    return sum(count_non_zero(row) for row in graph) // 2 # type: ignore
for me personally
`sum(sum(element for element in row if element > 0) for row in graph) // 2`
would be way more readable, and u could remove `#type: ignore`

2021-06-23 18:50 UTC, songofroland commented on graph_coloring/graph_utils.py
> +def pretty_print_graph(graph: AdjMatrix) -> None:
https://docs.python.org/3/library/pprint.html

2021-06-23 18:50 UTC, songofroland commented on graph_coloring/outputting.py
> +from json import dumps
wrong import order

2021-06-23 18:50 UTC, songofroland commented on graph_coloring/outputting.py
> +def output_results(colored_graph: AdjMatrix, vertex_labels: List[int]) -> None:
`colored_vertices` (adjective, plural noun) is more understandable than `vertex_labels` (singular noun, plural noun)

`labels_of_vertices ` would make more sense

2021-06-24 11:44 UTC, wilmhit commented on graph_coloring/graph_utils.py
> +    return sum(count_non_zero(row) for row in graph) // 2 # type: ignore
Your implementation works only if there are only `1` or `0` in the AdjMatrix. Mine is counting booleans. I remember this being important.

2021-06-24 11:45 UTC, wilmhit commented on graph_coloring/graph_utils.py
> +def pretty_print_graph(graph: AdjMatrix) -> None:
Nice

2021-06-24 11:46 UTC, wilmhit commented on graph_coloring/outputting.py
> +def output_results(colored_graph: AdjMatrix, vertex_labels: List[int]) -> None:
I don't really see it but if you say so.

2021-06-24 11:47 UTC, wilmhit commented on graph_coloring/graph_utils.py
> +    return sum(count_non_zero(row) for row in graph) // 2 # type: ignore
Ill go with 
```python
 sum(sum(element > 0 for element in row) for row in graph) // 2
```

2021-06-24 11:48 UTC, wilmhit commented on graph_coloring/graph_utils.py
> +def pretty_print_graph(graph: AdjMatrix) -> None:
It's not really needed now. I used it for debugging. Left it for future debugging. Gonna delete now.

2021-06-24 11:50 UTC, wilmhit commented
> I'd approve this, but due to MR order and function `get_edges_and_labels` I can't

You don't have to care about order. I branched this from your branch for that exact reason.

2021-06-24 15:43 UTC, songofroland commented
> > I'd approve this, but due to MR order and function `get_edges_and_labels` I can't
> 
> You don't have to care about order. I branched this from your branch for that exact reason.

Yeah I know, but I prefer to see the diffing files before approve

2021-06-24 15:51 UTC, songofroland requested changes

2021-06-24 15:51 UTC, songofroland commented on graph_coloring/graph_utils.py
> +from typing import Tuple
import order

2021-06-24 15:51 UTC, songofroland commented on graph_coloring/outputting.py
> +            edge = edge_indexes_to_labels(*edge_by_indexes)
Now it's neat!

However, this way it would be a lot more simpler:

```
def get_edges_and_labels(graph: AdjMatrix, labels_of_vertices: List[int]) -> Tuple[List[Edge], EdgeLabels]:
    edges: List[Edge] = []
    labels: EdgeLabels = {}

    for color, row, column in enumerate_half_graph(graph):
        if color:
            edge = (labels_of_vertices[row], labels_of_vertices[column]) 
            edges.append(edge)
            labels[edge] = color
            
    return edges, labels
```

2021-06-26 13:47 UTC, wilmhit commented
Gonna do edge/vertices printing in separate merge

2021-06-26 13:57 UTC, songofroland commented on Makefile
> +isort:
nice

2021-06-26 13:57 UTC, songofroland approved these changes

2021-06-26 15:34 UTC, merged