Graph parsing
wilmhit/elegant-graph-coloring pull request #2
Opened 2021-05-18 16:31 UTC by wilmhit

2021-05-23 14:17 UTC, songofroland requested changes

2021-05-23 14:17 UTC, songofroland commented on graph-coloring/graph_parsing.py
> +
```
    graph = []
    for line in graph_file.split("\n"):
        cells = line.split(" ") 
        # I don't get what's remove_empty_cells for
        graph.append([int(cell) for cell in cells])
    return graph
```
We don't need those functions. Python is idiomatic on its own.

To consider: using numpy (the question is if we'll take advantage of it - 16MB)
```
lines = graph_file.split("\n")
graph = [list(numpy.fromstring(line, dtype=int, sep="  ")) for line in lines]
```

2021-05-23 14:17 UTC, songofroland commented on graph-coloring/types.py
> +Graph = list[list[int]]
a big + for setting up static analysis tool

2021-05-24 12:05 UTC, wilmhit commented on Pipfile
> +yapf = "*"
pep8. It's default

2021-05-24 12:08 UTC, wilmhit commented on graph-coloring/__main__.py
> +def process_graph(graph: Graph) -> Idk:
It will be changed once this does something.

2021-05-24 12:13 UTC, wilmhit commented on graph-coloring/graph_parsing.py
> +
Numpy is definitely overkill for this project. Empty cells appear when there is double space in  input file.

2021-05-25 06:38 UTC, songofroland approved these changes

2021-05-25 06:38 UTC, songofroland commented on graph-coloring/file_operations.py
> +from customtypes import Idk
typo in import I guess

2021-05-25 06:38 UTC, songofroland commented on graph-coloring/graph_parsing.py
> +    """String must be separated with spaces and \n"""
```
The string should represent an adjacency matrix, separated with spaces and "\n",
e.g.
0 1 1 \n
1 0 1 \n
1 1 0 \n
```

2021-05-25 09:59 UTC, merged