Graph loading & graph validation
wilmhit/elegant-graph-coloring pull request #4
Opened 2021-05-25 14:29 UTC by wilmhit

2021-05-25 17:54 UTC, songofroland requested changes

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/__main__.py
> +    results: Idk = process_graph(graph)
the type is not needed here

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/__main__.py
> +    if error:
```
if error := get_error(graph)
    exit(error)
```

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/file_operations.py
> +    assert stat(filename).st_size < MAX_FILE_SIZE, "File is too big"
`The provided file is too big`

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/file_operations.py
> +def get_graph_file(filename: str) -> str:
rather `get_raw_graph` or `get_graph_string`

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_parsing.py
>      The string should represent an adjacency matrix, separated with spaces and \\n:
```
 """
The string should represent an adjacency matrix, separated with spaces and "\n".

Example:
 \n0 1 1\n1 0 1\n1 1 0
"""
```

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_parsing.py
> +    graph_file = graph_file.strip()
`graph_file` is not the best name here, it's not a file actually

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_validation.py
> +    """Retruns user-friendly error message or None"""
redundant, the name and returned type are descriptive enough

Also, how about:

`get_error_if_not_valid_graph`

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_validation.py
> +        return "This graph has not square"
_The provided graph is not a valid square_

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_validation.py
> +        return "Diagonal must consist only of zeros"
_The provided graph should only have zeros on its diagonal_

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_validation.py
> +    return True
`return any(len(row) != len(graph) for row in graph)`

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_validation.py
> +    for x in range(len(graph)):
here let's use `all` respectively

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/minizinc_script.py
> +def process_graph(graph: Graph) -> Idk:
let's just name it `get_colored_graph`

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/minizinc_script.py
> +    """ TODO doccomment this """
I hate comments, as you probably noticed 😉

2021-05-25 17:54 UTC, songofroland commented on test_graph.txt
> +
let's create a dir for this

2021-05-25 17:54 UTC, songofroland commented on graph-coloring/graph_validation.py
> +    """Retruns user-friendly error message or None"""
Alternatively, this would make a lot sense here:
`https://docs.python.org/3/library/doctest.html`

(Optional for you)

2021-05-25 18:01 UTC, wilmhit commented on graph-coloring/graph_validation.py
> +    """Retruns user-friendly error message or None"""
I actually knew about this lib, but this type of doccomment is not readable for me.

2021-05-25 18:04 UTC, wilmhit commented on graph-coloring/graph_validation.py
> +        return "This graph has not square"
Wtf did I write xD

2021-05-25 18:14 UTC, songofroland commented on graph-coloring/graph_validation.py
> +        return "This graph has not square"
Saw worse things made by seniors xD

2021-05-26 11:21 UTC, wilmhit commented on graph-coloring/minizinc_script.py
> +def process_graph(graph: Graph) -> Idk:
I'll leave it to another pull request. The one with minizinc.

2021-05-26 11:25 UTC, wilmhit commented on graph-coloring/minizinc_script.py
> +    """ TODO doccomment this """
I hate comments in code. But IDEs tooltips are too nice, so my practice is to doccomment "exported" functions. Yes I know - maintenance. But if doccomment is not too long it shouldn't be a problem.

2021-05-26 11:26 UTC, wilmhit commented on test_graph.txt
> +
I will make some tests later, so i'll do it then.

2021-05-26 18:51 UTC, songofroland approved these changes

2021-05-26 18:51 UTC, songofroland commented on graph-coloring/__main__.py
> +    if error := get_error_if_not_valid(graph):
Perfect, just rename `not_valid` -> `invalid`

2021-05-26 18:51 UTC, songofroland commented on graph-coloring/file_operations.py
> +    assert stat(filename).st_size < MAX_FILE_SIZE, "Provided file is too big"
if length was the limit, you can always do sth like:
```
error_msg = "The provided filed is too big"
assert stat(filename).st_size < MAX_FILE_SIZE, error_msg
```

2021-05-26 18:51 UTC, songofroland commented on graph-coloring/graph_validation.py
> +        return "Provided graph should only have zeros on its diagonal"
Why u decided not to use the definite article?  It's only uni projects so fuck it, but commercially I'd insist

2021-05-28 15:34 UTC, wilmhit commented on graph-coloring/file_operations.py
> +    assert stat(filename).st_size < MAX_FILE_SIZE, "Provided file is too big"
No, this is what I wanted to write

2021-05-28 15:36 UTC, wilmhit commented on graph-coloring/graph_validation.py
> +        return "Provided graph should only have zeros on its diagonal"
Why?

2021-05-28 15:40 UTC, wilmhit commented on graph-coloring/graph_validation.py
> +        return "Provided graph should only have zeros on its diagonal"
Either way this makes correct English sentence. I don't have any particular view on using it or not.

2021-05-28 15:47 UTC, merged

2021-05-28 17:17 UTC, songofroland commented on graph-coloring/graph_validation.py
> +        return "Provided graph should only have zeros on its diagonal"
Random example from AWS docs:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/error-handling.html#catching-botocore-exceptions

This is the kind of detail that seniors always pointed me out