Implement elegant coloring, adjust package imports
wilmhit/elegant-graph-coloring pull request #5
Opened 2021-05-29 18:55 UTC by songofroland

2021-05-29 19:57 UTC, wilmhit requested changes
Is `__init__.py` needed in test folder?

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/coloring.py
> +def get_colored_edges(graph: AdjMatrix) -> AdjMatrix:
the name suggests it returns list of edges.

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/models/elegant_labeling.mzn
> +                  );
I don't think i'm qualified enough to review this file

2021-05-29 19:57 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    "invalid_graph",
why this graph is invalid?

2021-05-29 19:57 UTC, wilmhit commented on tests/test_graph_coloring.py
> +def test_error_raised_when_graph_could_not_be_solved(invalid_graph: AdjMatrix):
Why could not be solved?

2021-05-29 19:57 UTC, wilmhit commented on tests/test_graph_coloring.py
> +def test__graph__colored_correctly(graph: AdjMatrix, expected_coloring: AdjMatrix):
is double floor a mistake here?

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/sample_graphs.py
> +SHAK_F_4 = {
SHACK

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/coloring.py
> +    model_path = Path(__file__).parent.absolute().joinpath("models/elegant_labeling.mzn")
I would split it to CONSTANT named BASEDIR and then 
```
BASEDIR.joinpath("...")
```

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/coloring.py
> +    model_path = Path(__file__).parent.absolute().joinpath("models/elegant_labeling.mzn")
BASEPATH would be a better name

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/coloring.py
> +    instance["total_edges"] = sum(row.count(1) for row in graph) // 2
the sum is going to be 2? doesn't this depend on graph size?

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/coloring.py
> +    return result["coloring"]  # type: ignore
have you tried using `as` keyword to check type? mypy also supports checking type with `if isinstance`.

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/coloring.py
> +        error_message = f"An error occured when coloring the graph. Returned status: {status}"
If statuse is enum I would assume they are some arbitrary integers underneath (non-human readable or dynamic). In this case throwing this integer does not make sense unless it's excepted somewhere higher in call stack.

2021-05-29 19:57 UTC, wilmhit commented on graph_coloring/__main__.py
> +from .file_operations import get_graph_string
`__main__.py` is not part of a package so relative imports do not work in this file. This would need to be moved to `__init__.py` to work now.

2021-05-30 12:27 UTC, songofroland commented on tests/test_graph_coloring.py
> +    "invalid_graph",
Not every graph will be easily colorable.

It could be valid if we were to color the vertices too, but that will require a lot of changes throughout the package.

2021-05-30 12:27 UTC, songofroland commented on tests/test_graph_coloring.py
> +def test_error_raised_when_graph_could_not_be_solved(invalid_graph: AdjMatrix):
up

2021-05-30 12:31 UTC, songofroland commented on graph_coloring/coloring.py
> +    instance["total_edges"] = sum(row.count(1) for row in graph) // 2
Why 2? It's an integer division, not a comment 😉

2021-05-30 12:33 UTC, songofroland commented on graph_coloring/coloring.py
> +    return result["coloring"]  # type: ignore
Nope, how to do that? I think we don't need to focus on such a minor details tho

2021-05-30 12:34 UTC, songofroland commented on graph_coloring/coloring.py
> +        error_message = f"An error occured when coloring the graph. Returned status: {status}"
it's a string sow I'd keep it. We can adjust it later on after comprehensive tests

2021-05-30 12:53 UTC, songofroland commented on graph_coloring/__main__.py
> +from .file_operations import get_graph_string
It works on my machine
<img width="1130" alt="Screenshot 2021-05-30 at 14 53 37" src="https://user-images.githubusercontent.com/46332508/120104843-d338df00-c156-11eb-88f6-7805541a82af.png">

2021-05-30 13:01 UTC, songofroland commented on graph_coloring/coloring.py
> +    model_path = Path(__file__).parent.absolute().joinpath("models/elegant_labeling.mzn")
I've made BASE_DIR bc of django

2021-05-30 13:37 UTC, wilmhit commented on graph_coloring/coloring.py
> +    model_path = Path(__file__).parent.absolute().joinpath("models/elegant_labeling.mzn")
BASE_DIR is usually string not path object but that's fine.

2021-05-30 13:38 UTC, wilmhit commented on graph_coloring/coloring.py
> +    instance["total_edges"] = sum(row.count(1) for row in graph) // 2
Right. Too much js

2021-05-30 13:42 UTC, wilmhit commented on graph_coloring/coloring.py
> +    return result["coloring"]  # type: ignore
Again I've mistaken typescript's `as` with python. Sure, `isinstance` would be too much here, but ` # type: AdjMatrix` here would be better than ignore.

2021-05-30 13:50 UTC, wilmhit commented on graph_coloring/graph_parsing.py
> +def to_cells(line: str) -> List[int]:
We are targeting python 3.9 so `list` is fine

2021-05-30 13:50 UTC, wilmhit commented on tests/test_graph_coloring.py
> +    "invalid_graph",
I would expect a reason why it's `non_colorable`, but if it's too complicated, then thats fine.

2021-05-30 13:54 UTC, wilmhit commented on graph_coloring/__main__.py
> +from .file_operations import get_graph_string
Yes this works with `-m` parameter, previously it was working without it. That's fine.

2021-05-30 13:58 UTC, wilmhit requested changes
Also look at replies above.

2021-05-30 14:08 UTC, songofroland commented on graph_coloring/graph_parsing.py
> +def to_cells(line: str) -> List[int]:
I'm sometimes running 3.8, using `List` won't hurt.

2021-05-30 14:09 UTC, songofroland commented on graph_coloring/coloring.py
> +    return result["coloring"]  # type: ignore
fair point

2021-05-30 14:12 UTC, songofroland commented on tests/test_graph_coloring.py
> +    "invalid_graph",
It rather should not be described here

2021-05-30 14:20 UTC, songofroland commented
> Is `__init__.py` needed in test folder?

I like that It will mark the dir as a python package

2021-05-30 15:41 UTC, wilmhit approved these changes

2021-05-30 21:14 UTC, merged